name: Rust - Run Clippy to check lints
on:
    # Check whenever a file that affects Rust formatting is changed in a pull request
    pull_request:
        paths:
            - .github/workflows/clippy.yml
            - clippy.toml
            - '**/*.rs'
    # Check if requested manually from the Actions tab
    workflow_dispatch:
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1.0.6
        with:
            toolchain: nightly
            components: clippy
            override: true
      - uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --all-features
